// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: pp-client.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Toqe.PortfolioReader.Business.Protobuf
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PDecimalValue : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"scale")]
        public uint Scale { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"precision")]
        public uint Precision { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"value")]
        public byte[] Value { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PAnyValue : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"null")]
        public global::Google.Protobuf.WellKnownTypes.NullValue Null
        {
            get => __pbn__kind.Is(1) ? ((global::Google.Protobuf.WellKnownTypes.NullValue)__pbn__kind.Int32) : default;
            set => __pbn__kind = new global::ProtoBuf.DiscriminatedUnion64Object(1, (int)value);
        }
        public bool ShouldSerializeNull() => __pbn__kind.Is(1);
        public void ResetNull() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__kind, 1);

        private global::ProtoBuf.DiscriminatedUnion64Object __pbn__kind;

        [global::ProtoBuf.ProtoMember(2, Name = @"string")]
        [global::System.ComponentModel.DefaultValue("")]
        public string String
        {
            get => __pbn__kind.Is(2) ? ((string)__pbn__kind.Object) : "";
            set => __pbn__kind = new global::ProtoBuf.DiscriminatedUnion64Object(2, value);
        }
        public bool ShouldSerializeString() => __pbn__kind.Is(2);
        public void ResetString() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__kind, 2);

        [global::ProtoBuf.ProtoMember(3, Name = @"int32")]
        public int Int32
        {
            get => __pbn__kind.Is(3) ? __pbn__kind.Int32 : default;
            set => __pbn__kind = new global::ProtoBuf.DiscriminatedUnion64Object(3, value);
        }
        public bool ShouldSerializeInt32() => __pbn__kind.Is(3);
        public void ResetInt32() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__kind, 3);

        [global::ProtoBuf.ProtoMember(4, Name = @"int64")]
        public long Int64
        {
            get => __pbn__kind.Is(4) ? __pbn__kind.Int64 : default;
            set => __pbn__kind = new global::ProtoBuf.DiscriminatedUnion64Object(4, value);
        }
        public bool ShouldSerializeInt64() => __pbn__kind.Is(4);
        public void ResetInt64() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__kind, 4);

        [global::ProtoBuf.ProtoMember(5, Name = @"double")]
        public double Double
        {
            get => __pbn__kind.Is(5) ? __pbn__kind.Double : default;
            set => __pbn__kind = new global::ProtoBuf.DiscriminatedUnion64Object(5, value);
        }
        public bool ShouldSerializeDouble() => __pbn__kind.Is(5);
        public void ResetDouble() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__kind, 5);

        [global::ProtoBuf.ProtoMember(6, Name = @"bool")]
        public bool Bool
        {
            get => __pbn__kind.Is(6) ? __pbn__kind.Boolean : default;
            set => __pbn__kind = new global::ProtoBuf.DiscriminatedUnion64Object(6, value);
        }
        public bool ShouldSerializeBool() => __pbn__kind.Is(6);
        public void ResetBool() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__kind, 6);

        [global::ProtoBuf.ProtoMember(7, Name = @"map")]
        public PMap Map
        {
            get => __pbn__kind.Is(7) ? ((PMap)__pbn__kind.Object) : default;
            set => __pbn__kind = new global::ProtoBuf.DiscriminatedUnion64Object(7, value);
        }
        public bool ShouldSerializeMap() => __pbn__kind.Is(7);
        public void ResetMap() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__kind, 7);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PKeyValue : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"key")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Key { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"value")]
        public PAnyValue Value { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PMap : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"entries")]
        public global::System.Collections.Generic.List<PKeyValue> Entries { get; } = new global::System.Collections.Generic.List<PKeyValue>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PHistoricalPrice : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"date")]
        public long Date { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"close")]
        public long Close { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PFullHistoricalPrice : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"date")]
        public long Date { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"close")]
        public long Close { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"high")]
        public long High { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"low")]
        public long Low { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"volume")]
        public long Volume { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PSecurityEvent : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Type type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"date")]
        public long Date { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"details")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Details { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"data")]
        public global::System.Collections.Generic.List<PAnyValue> Datas { get; } = new global::System.Collections.Generic.List<PAnyValue>();

        [global::ProtoBuf.ProtoMember(5, Name = @"source")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Source { get; set; } = "";

        [global::ProtoBuf.ProtoContract()]
        public enum Type
        {
            [global::ProtoBuf.ProtoEnum(Name = @"STOCK_SPLIT")]
            StockSplit = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"NOTE")]
            Note = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"DIVIDEND_PAYMENT")]
            DividendPayment = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PSecurity : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uuid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Uuid { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string onlineId
        {
            get => __pbn__onlineId ?? "";
            set => __pbn__onlineId = value;
        }
        public bool ShouldSerializeonlineId() => __pbn__onlineId != null;
        public void ResetonlineId() => __pbn__onlineId = null;
        private string __pbn__onlineId;

        [global::ProtoBuf.ProtoMember(3, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string currencyCode
        {
            get => __pbn__currencyCode ?? "";
            set => __pbn__currencyCode = value;
        }
        public bool ShouldSerializecurrencyCode() => __pbn__currencyCode != null;
        public void ResetcurrencyCode() => __pbn__currencyCode = null;
        private string __pbn__currencyCode;

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string targetCurrencyCode
        {
            get => __pbn__targetCurrencyCode ?? "";
            set => __pbn__targetCurrencyCode = value;
        }
        public bool ShouldSerializetargetCurrencyCode() => __pbn__targetCurrencyCode != null;
        public void ResettargetCurrencyCode() => __pbn__targetCurrencyCode = null;
        private string __pbn__targetCurrencyCode;

        [global::ProtoBuf.ProtoMember(6, Name = @"note")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Note
        {
            get => __pbn__Note ?? "";
            set => __pbn__Note = value;
        }
        public bool ShouldSerializeNote() => __pbn__Note != null;
        public void ResetNote() => __pbn__Note = null;
        private string __pbn__Note;

        [global::ProtoBuf.ProtoMember(7, Name = @"isin")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Isin
        {
            get => __pbn__Isin ?? "";
            set => __pbn__Isin = value;
        }
        public bool ShouldSerializeIsin() => __pbn__Isin != null;
        public void ResetIsin() => __pbn__Isin = null;
        private string __pbn__Isin;

        [global::ProtoBuf.ProtoMember(8)]
        [global::System.ComponentModel.DefaultValue("")]
        public string tickerSymbol
        {
            get => __pbn__tickerSymbol ?? "";
            set => __pbn__tickerSymbol = value;
        }
        public bool ShouldSerializetickerSymbol() => __pbn__tickerSymbol != null;
        public void ResettickerSymbol() => __pbn__tickerSymbol = null;
        private string __pbn__tickerSymbol;

        [global::ProtoBuf.ProtoMember(9, Name = @"wkn")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Wkn
        {
            get => __pbn__Wkn ?? "";
            set => __pbn__Wkn = value;
        }
        public bool ShouldSerializeWkn() => __pbn__Wkn != null;
        public void ResetWkn() => __pbn__Wkn = null;
        private string __pbn__Wkn;

        [global::ProtoBuf.ProtoMember(10, Name = @"calendar")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Calendar
        {
            get => __pbn__Calendar ?? "";
            set => __pbn__Calendar = value;
        }
        public bool ShouldSerializeCalendar() => __pbn__Calendar != null;
        public void ResetCalendar() => __pbn__Calendar = null;
        private string __pbn__Calendar;

        [global::ProtoBuf.ProtoMember(11, Name = @"feed")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Feed
        {
            get => __pbn__Feed ?? "";
            set => __pbn__Feed = value;
        }
        public bool ShouldSerializeFeed() => __pbn__Feed != null;
        public void ResetFeed() => __pbn__Feed = null;
        private string __pbn__Feed;

        [global::ProtoBuf.ProtoMember(12)]
        [global::System.ComponentModel.DefaultValue("")]
        public string feedURL
        {
            get => __pbn__feedURL ?? "";
            set => __pbn__feedURL = value;
        }
        public bool ShouldSerializefeedURL() => __pbn__feedURL != null;
        public void ResetfeedURL() => __pbn__feedURL = null;
        private string __pbn__feedURL;

        [global::ProtoBuf.ProtoMember(13, Name = @"prices")]
        public global::System.Collections.Generic.List<PHistoricalPrice> Prices { get; } = new global::System.Collections.Generic.List<PHistoricalPrice>();

        [global::ProtoBuf.ProtoMember(14)]
        [global::System.ComponentModel.DefaultValue("")]
        public string latestFeed
        {
            get => __pbn__latestFeed ?? "";
            set => __pbn__latestFeed = value;
        }
        public bool ShouldSerializelatestFeed() => __pbn__latestFeed != null;
        public void ResetlatestFeed() => __pbn__latestFeed = null;
        private string __pbn__latestFeed;

        [global::ProtoBuf.ProtoMember(15)]
        [global::System.ComponentModel.DefaultValue("")]
        public string latestFeedURL
        {
            get => __pbn__latestFeedURL ?? "";
            set => __pbn__latestFeedURL = value;
        }
        public bool ShouldSerializelatestFeedURL() => __pbn__latestFeedURL != null;
        public void ResetlatestFeedURL() => __pbn__latestFeedURL = null;
        private string __pbn__latestFeedURL;

        [global::ProtoBuf.ProtoMember(16, Name = @"latest")]
        public PFullHistoricalPrice Latest { get; set; }

        [global::ProtoBuf.ProtoMember(17, Name = @"attributes")]
        public global::System.Collections.Generic.List<PKeyValue> Attributes { get; } = new global::System.Collections.Generic.List<PKeyValue>();

        [global::ProtoBuf.ProtoMember(18, Name = @"events")]
        public global::System.Collections.Generic.List<PSecurityEvent> Events { get; } = new global::System.Collections.Generic.List<PSecurityEvent>();

        [global::ProtoBuf.ProtoMember(19, Name = @"properties")]
        public global::System.Collections.Generic.List<PKeyValue> Properties { get; } = new global::System.Collections.Generic.List<PKeyValue>();

        [global::ProtoBuf.ProtoMember(20)]
        public bool isRetired { get; set; }

        [global::ProtoBuf.ProtoMember(21)]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.DateTime? updatedAt { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PWatchlist : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"securities")]
        public global::System.Collections.Generic.List<string> Securities { get; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PAccount : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uuid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Uuid { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string currencyCode { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"note")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Note
        {
            get => __pbn__Note ?? "";
            set => __pbn__Note = value;
        }
        public bool ShouldSerializeNote() => __pbn__Note != null;
        public void ResetNote() => __pbn__Note = null;
        private string __pbn__Note;

        [global::ProtoBuf.ProtoMember(5)]
        public bool isRetired { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"attributes")]
        public global::System.Collections.Generic.List<PKeyValue> Attributes { get; } = new global::System.Collections.Generic.List<PKeyValue>();

        [global::ProtoBuf.ProtoMember(7)]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.DateTime? updatedAt { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PPortfolio : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uuid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Uuid { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"note")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Note
        {
            get => __pbn__Note ?? "";
            set => __pbn__Note = value;
        }
        public bool ShouldSerializeNote() => __pbn__Note != null;
        public void ResetNote() => __pbn__Note = null;
        private string __pbn__Note;

        [global::ProtoBuf.ProtoMember(4)]
        public bool isRetired { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string referenceAccount
        {
            get => __pbn__referenceAccount ?? "";
            set => __pbn__referenceAccount = value;
        }
        public bool ShouldSerializereferenceAccount() => __pbn__referenceAccount != null;
        public void ResetreferenceAccount() => __pbn__referenceAccount = null;
        private string __pbn__referenceAccount;

        [global::ProtoBuf.ProtoMember(6, Name = @"attributes")]
        public global::System.Collections.Generic.List<PKeyValue> Attributes { get; } = new global::System.Collections.Generic.List<PKeyValue>();

        [global::ProtoBuf.ProtoMember(7)]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.DateTime? updatedAt { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PTransactionUnit : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Type type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"amount")]
        public long Amount { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string currencyCode { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4)]
        public long fxAmount
        {
            get => __pbn__fxAmount.GetValueOrDefault();
            set => __pbn__fxAmount = value;
        }
        public bool ShouldSerializefxAmount() => __pbn__fxAmount != null;
        public void ResetfxAmount() => __pbn__fxAmount = null;
        private long? __pbn__fxAmount;

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string fxCurrencyCode
        {
            get => __pbn__fxCurrencyCode ?? "";
            set => __pbn__fxCurrencyCode = value;
        }
        public bool ShouldSerializefxCurrencyCode() => __pbn__fxCurrencyCode != null;
        public void ResetfxCurrencyCode() => __pbn__fxCurrencyCode = null;
        private string __pbn__fxCurrencyCode;

        [global::ProtoBuf.ProtoMember(6)]
        public PDecimalValue fxRateToBase { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Type
        {
            [global::ProtoBuf.ProtoEnum(Name = @"GROSS_VALUE")]
            GrossValue = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"TAX")]
            Tax = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"FEE")]
            Fee = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PTransaction : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uuid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Uuid { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public Type type { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"account")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Account
        {
            get => __pbn__Account ?? "";
            set => __pbn__Account = value;
        }
        public bool ShouldSerializeAccount() => __pbn__Account != null;
        public void ResetAccount() => __pbn__Account = null;
        private string __pbn__Account;

        [global::ProtoBuf.ProtoMember(4, Name = @"portfolio")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Portfolio
        {
            get => __pbn__Portfolio ?? "";
            set => __pbn__Portfolio = value;
        }
        public bool ShouldSerializePortfolio() => __pbn__Portfolio != null;
        public void ResetPortfolio() => __pbn__Portfolio = null;
        private string __pbn__Portfolio;

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string otherAccount
        {
            get => __pbn__otherAccount ?? "";
            set => __pbn__otherAccount = value;
        }
        public bool ShouldSerializeotherAccount() => __pbn__otherAccount != null;
        public void ResetotherAccount() => __pbn__otherAccount = null;
        private string __pbn__otherAccount;

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string otherPortfolio
        {
            get => __pbn__otherPortfolio ?? "";
            set => __pbn__otherPortfolio = value;
        }
        public bool ShouldSerializeotherPortfolio() => __pbn__otherPortfolio != null;
        public void ResetotherPortfolio() => __pbn__otherPortfolio = null;
        private string __pbn__otherPortfolio;

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue("")]
        public string otherUuid
        {
            get => __pbn__otherUuid ?? "";
            set => __pbn__otherUuid = value;
        }
        public bool ShouldSerializeotherUuid() => __pbn__otherUuid != null;
        public void ResetotherUuid() => __pbn__otherUuid = null;
        private string __pbn__otherUuid;

        [global::ProtoBuf.ProtoMember(8)]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.DateTime? otherUpdatedAt { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"date")]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.DateTime? Date { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        [global::System.ComponentModel.DefaultValue("")]
        public string currencyCode { get; set; } = "";

        [global::ProtoBuf.ProtoMember(11, Name = @"amount")]
        public long Amount { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"shares")]
        public long Shares
        {
            get => __pbn__Shares.GetValueOrDefault();
            set => __pbn__Shares = value;
        }
        public bool ShouldSerializeShares() => __pbn__Shares != null;
        public void ResetShares() => __pbn__Shares = null;
        private long? __pbn__Shares;

        [global::ProtoBuf.ProtoMember(13, Name = @"note")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Note
        {
            get => __pbn__Note ?? "";
            set => __pbn__Note = value;
        }
        public bool ShouldSerializeNote() => __pbn__Note != null;
        public void ResetNote() => __pbn__Note = null;
        private string __pbn__Note;

        [global::ProtoBuf.ProtoMember(14, Name = @"security")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Security
        {
            get => __pbn__Security ?? "";
            set => __pbn__Security = value;
        }
        public bool ShouldSerializeSecurity() => __pbn__Security != null;
        public void ResetSecurity() => __pbn__Security = null;
        private string __pbn__Security;

        [global::ProtoBuf.ProtoMember(15, Name = @"units")]
        public global::System.Collections.Generic.List<PTransactionUnit> Units { get; } = new global::System.Collections.Generic.List<PTransactionUnit>();

        [global::ProtoBuf.ProtoMember(16)]
        [global::ProtoBuf.CompatibilityLevel(global::ProtoBuf.CompatibilityLevel.Level300)]
        public global::System.DateTime? updatedAt { get; set; }

        [global::ProtoBuf.ProtoMember(17, Name = @"source")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Source
        {
            get => __pbn__Source ?? "";
            set => __pbn__Source = value;
        }
        public bool ShouldSerializeSource() => __pbn__Source != null;
        public void ResetSource() => __pbn__Source = null;
        private string __pbn__Source;

        [global::ProtoBuf.ProtoContract()]
        public enum Type
        {
            [global::ProtoBuf.ProtoEnum(Name = @"PURCHASE")]
            Purchase = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"SALE")]
            Sale = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"INBOUND_DELIVERY")]
            InboundDelivery = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"OUTBOUND_DELIVERY")]
            OutboundDelivery = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"SECURITY_TRANSFER")]
            SecurityTransfer = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"CASH_TRANSFER")]
            CashTransfer = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"DEPOSIT")]
            Deposit = 6,
            [global::ProtoBuf.ProtoEnum(Name = @"REMOVAL")]
            Removal = 7,
            [global::ProtoBuf.ProtoEnum(Name = @"DIVIDEND")]
            Dividend = 8,
            [global::ProtoBuf.ProtoEnum(Name = @"INTEREST")]
            Interest = 9,
            [global::ProtoBuf.ProtoEnum(Name = @"INTEREST_CHARGE")]
            InterestCharge = 10,
            [global::ProtoBuf.ProtoEnum(Name = @"TAX")]
            Tax = 11,
            [global::ProtoBuf.ProtoEnum(Name = @"TAX_REFUND")]
            TaxRefund = 12,
            [global::ProtoBuf.ProtoEnum(Name = @"FEE")]
            Fee = 13,
            [global::ProtoBuf.ProtoEnum(Name = @"FEE_REFUND")]
            FeeRefund = 14,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PInvestmentPlan : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"note")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Note
        {
            get => __pbn__Note ?? "";
            set => __pbn__Note = value;
        }
        public bool ShouldSerializeNote() => __pbn__Note != null;
        public void ResetNote() => __pbn__Note = null;
        private string __pbn__Note;

        [global::ProtoBuf.ProtoMember(3, Name = @"security")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Security
        {
            get => __pbn__Security ?? "";
            set => __pbn__Security = value;
        }
        public bool ShouldSerializeSecurity() => __pbn__Security != null;
        public void ResetSecurity() => __pbn__Security = null;
        private string __pbn__Security;

        [global::ProtoBuf.ProtoMember(4, Name = @"portfolio")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Portfolio
        {
            get => __pbn__Portfolio ?? "";
            set => __pbn__Portfolio = value;
        }
        public bool ShouldSerializePortfolio() => __pbn__Portfolio != null;
        public void ResetPortfolio() => __pbn__Portfolio = null;
        private string __pbn__Portfolio;

        [global::ProtoBuf.ProtoMember(5, Name = @"account")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Account
        {
            get => __pbn__Account ?? "";
            set => __pbn__Account = value;
        }
        public bool ShouldSerializeAccount() => __pbn__Account != null;
        public void ResetAccount() => __pbn__Account = null;
        private string __pbn__Account;

        [global::ProtoBuf.ProtoMember(6, Name = @"attributes")]
        public global::System.Collections.Generic.List<PKeyValue> Attributes { get; } = new global::System.Collections.Generic.List<PKeyValue>();

        [global::ProtoBuf.ProtoMember(7)]
        public bool autoGenerate { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"date")]
        public long Date { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"interval")]
        public int Interval { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"amount")]
        public long Amount { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"fees")]
        public long Fees { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"transactions")]
        public global::System.Collections.Generic.List<string> Transactions { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(13, Name = @"taxes")]
        public long Taxes { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        public Type type { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Type
        {
            [global::ProtoBuf.ProtoEnum(Name = @"PURCHASE_OR_DELIVERY")]
            PurchaseOrDelivery = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"DEPOSIT")]
            Deposit = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"REMOVAL")]
            Removal = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"INTEREST")]
            Interest = 3,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PTaxonomy : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"source")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Source
        {
            get => __pbn__Source ?? "";
            set => __pbn__Source = value;
        }
        public bool ShouldSerializeSource() => __pbn__Source != null;
        public void ResetSource() => __pbn__Source = null;
        private string __pbn__Source;

        [global::ProtoBuf.ProtoMember(4, Name = @"dimensions")]
        public global::System.Collections.Generic.List<string> Dimensions { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(5, Name = @"classifications")]
        public global::System.Collections.Generic.List<Classification> Classifications { get; } = new global::System.Collections.Generic.List<Classification>();

        [global::ProtoBuf.ProtoContract()]
        public partial class Assignment : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            [global::System.ComponentModel.DefaultValue("")]
            public string investmentVehicle { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2, Name = @"weight")]
            public int Weight { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"rank")]
            public int Rank { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"data")]
            public global::System.Collections.Generic.List<PKeyValue> Datas { get; } = new global::System.Collections.Generic.List<PKeyValue>();

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Classification : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"id")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Id { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2)]
            [global::System.ComponentModel.DefaultValue("")]
            public string parentId
            {
                get => __pbn__parentId ?? "";
                set => __pbn__parentId = value;
            }
            public bool ShouldSerializeparentId() => __pbn__parentId != null;
            public void ResetparentId() => __pbn__parentId = null;
            private string __pbn__parentId;

            [global::ProtoBuf.ProtoMember(3, Name = @"name")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Name { get; set; } = "";

            [global::ProtoBuf.ProtoMember(4, Name = @"note")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Note
            {
                get => __pbn__Note ?? "";
                set => __pbn__Note = value;
            }
            public bool ShouldSerializeNote() => __pbn__Note != null;
            public void ResetNote() => __pbn__Note = null;
            private string __pbn__Note;

            [global::ProtoBuf.ProtoMember(5, Name = @"color")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Color { get; set; } = "";

            [global::ProtoBuf.ProtoMember(6, Name = @"weight")]
            public int Weight { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"rank")]
            public int Rank { get; set; }

            [global::ProtoBuf.ProtoMember(8, Name = @"data")]
            public global::System.Collections.Generic.List<PKeyValue> Datas { get; } = new global::System.Collections.Generic.List<PKeyValue>();

            [global::ProtoBuf.ProtoMember(9, Name = @"assignments")]
            public global::System.Collections.Generic.List<PTaxonomy.Assignment> Assignments { get; } = new global::System.Collections.Generic.List<PTaxonomy.Assignment>();

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PDashboard : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"configuration")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, string> Configurations { get; } = new global::System.Collections.Generic.Dictionary<string, string>();

        [global::ProtoBuf.ProtoMember(3, Name = @"columns")]
        public global::System.Collections.Generic.List<Column> Columns { get; } = new global::System.Collections.Generic.List<Column>();

        [global::ProtoBuf.ProtoMember(4, Name = @"id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Id { get; set; } = "";

        [global::ProtoBuf.ProtoContract()]
        public partial class Widget : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"type")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Type { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2, Name = @"label")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Label { get; set; } = "";

            [global::ProtoBuf.ProtoMember(3, Name = @"configuration")]
            [global::ProtoBuf.ProtoMap]
            public global::System.Collections.Generic.Dictionary<string, string> Configurations { get; } = new global::System.Collections.Generic.Dictionary<string, string>();

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Column : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"weight")]
            public int Weight { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"widgets")]
            public global::System.Collections.Generic.List<PDashboard.Widget> Widgets { get; } = new global::System.Collections.Generic.List<PDashboard.Widget>();

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PBookmark : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"label")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Label { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"pattern")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Pattern { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PAttributeType : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Id { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string columnLabel { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"source")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Source
        {
            get => __pbn__Source ?? "";
            set => __pbn__Source = value;
        }
        public bool ShouldSerializeSource() => __pbn__Source != null;
        public void ResetSource() => __pbn__Source = null;
        private string __pbn__Source;

        [global::ProtoBuf.ProtoMember(5, Name = @"target")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Target { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6, Name = @"type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Type { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue("")]
        public string converterClass { get; set; } = "";

        [global::ProtoBuf.ProtoMember(8, Name = @"properties")]
        public PMap Properties { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PConfigurationSet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"key")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Key { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"uuid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Uuid { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"data")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Data { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PSettings : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"bookmarks")]
        public global::System.Collections.Generic.List<PBookmark> Bookmarks { get; } = new global::System.Collections.Generic.List<PBookmark>();

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<PAttributeType> attributeTypes { get; } = new global::System.Collections.Generic.List<PAttributeType>();

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<PConfigurationSet> configurationSets { get; } = new global::System.Collections.Generic.List<PConfigurationSet>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PClient : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"version")]
        public int Version { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"securities")]
        public global::System.Collections.Generic.List<PSecurity> Securities { get; } = new global::System.Collections.Generic.List<PSecurity>();

        [global::ProtoBuf.ProtoMember(3, Name = @"accounts")]
        public global::System.Collections.Generic.List<PAccount> Accounts { get; } = new global::System.Collections.Generic.List<PAccount>();

        [global::ProtoBuf.ProtoMember(4, Name = @"portfolios")]
        public global::System.Collections.Generic.List<PPortfolio> Portfolios { get; } = new global::System.Collections.Generic.List<PPortfolio>();

        [global::ProtoBuf.ProtoMember(5, Name = @"transactions")]
        public global::System.Collections.Generic.List<PTransaction> Transactions { get; } = new global::System.Collections.Generic.List<PTransaction>();

        [global::ProtoBuf.ProtoMember(6, Name = @"plans")]
        public global::System.Collections.Generic.List<PInvestmentPlan> Plans { get; } = new global::System.Collections.Generic.List<PInvestmentPlan>();

        [global::ProtoBuf.ProtoMember(7, Name = @"watchlists")]
        public global::System.Collections.Generic.List<PWatchlist> Watchlists { get; } = new global::System.Collections.Generic.List<PWatchlist>();

        [global::ProtoBuf.ProtoMember(8, Name = @"taxonomies")]
        public global::System.Collections.Generic.List<PTaxonomy> Taxonomies { get; } = new global::System.Collections.Generic.List<PTaxonomy>();

        [global::ProtoBuf.ProtoMember(9, Name = @"dashboards")]
        public global::System.Collections.Generic.List<PDashboard> Dashboards { get; } = new global::System.Collections.Generic.List<PDashboard>();

        [global::ProtoBuf.ProtoMember(10, Name = @"properties")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, string> Properties { get; } = new global::System.Collections.Generic.Dictionary<string, string>();

        [global::ProtoBuf.ProtoMember(11, Name = @"settings")]
        public PSettings Settings { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        [global::System.ComponentModel.DefaultValue("")]
        public string baseCurrency { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PExchangeRate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"date")]
        public long Date { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"value")]
        public PDecimalValue Value { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PExchangeRateTimeSeries : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string baseCurrency { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string termCurrency { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<PExchangeRate> exchangeRates { get; } = new global::System.Collections.Generic.List<PExchangeRate>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PECBData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long lastModified { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"series")]
        public global::System.Collections.Generic.List<PExchangeRateTimeSeries> Series { get; } = new global::System.Collections.Generic.List<PExchangeRateTimeSeries>();

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
